---
- name: restart nginx
  service: name=nginx state=restarted
  when: nginx_service_management

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: false

- name: reload nginx
  service: name=nginx state=reloaded
  when:
    - nginx_service_management
    - nginx_service_state == "started"
